import { AppDefault } from "../../app/constants/AppDefault";


@ObservedV2
export class UserSettings {
  // @Trace currentBookId          : number                = AppDefault.InitialBookIndex

  // 列表配置
  // @Trace isListOneCircle        : boolean               = AppDefault.isCardCircle

  // 布局配置
  // @Trace boxPaperLandscape      : boolean               = true
  // @Trace boxSizeAmount          : number                = 88
  // @Trace boxFrameShow           : boolean               = true
  // @Trace boxFrameColorHex       : string                = "#FF0000"

  // 卡片配置
  // @Trace isCardFlipped          : boolean               = AppDefault.isCardFlipped
  // @Trace isCardAutoPron         : boolean               = AppDefault.isAutoPron
  // @Trace cardSoundPlayingType   : CardSoundPlayingType  = AppDefault.cardSoundPlayingType
  //
  // @Trace cardTypeFront          : CardType              = AppDefault.cardTypeFront
  // @Trace cardTypeBack           : CardType              = AppDefault.cardTypeBack

  //复习列表
  // @Trace isExcludeLearned       : boolean               = false
}

