export namespace  BaseWordConstants {
  export class  TitleTextJp {
    public static readonly  wordsSperator    = "；"; //翻译分隔符
    public static readonly  wordsSubSperator = "，"; //翻译子分隔符
    public static readonly  linesSeperator   = "\n"; //换行符
    public static readonly  wordsMaxPart     = 4;    //翻译最大部分数
    public static readonly  wordsMaxPartLong = 6;    //10; //翻译最大部分数(更长，用于BaseDict)
  }
}