

// 应用默认配置常量类
export class AppDefault {
  // 卡片形状配置
  // static readonly isCardCircle         : boolean               = false;

  // 书籍默认索引
  // static readonly InitialBookIndex     : number                = 2;

  // 发音配置
  // static readonly isAutoPron           : boolean               = false;
  // static readonly cardSoundPlayingType : CardSoundPlayingType  = CardSoundPlayingType.title_word_sentence;
  //
  // // 卡片状态
  // static readonly isCardFlipped        : boolean               = false;
  //
  // // 卡片样式
  // static readonly cardTypeFront        : CardType              = CardType.one; //expZwPyEn;
  // static readonly cardTypeBack         : CardType              = CardType.memo;
}